### ISSUE TITLE
Feature request: add a native GCS driver

### ISSUE THREAD

**Issue by Charles546** [honeydipper/honeydipper#111]
We need a driver that can list and fetch files from google cloud storage.

**Comment by mc422** [comment]
@Charles546 @wyardley  I can take this one

**Comment by mc422** [comment]
@Charles546 for the fetch file function, you need to fetch file and return the content of the file, right? If we are trying to fetch the content of the file, what format are you looking for?

**Comment by wyardley** [comment]
Also: we'll want to be pretty cautious about what we take from here and how.
Maybe we can require the file to be in certain formats and do some careful validation that it is what we expect, or throw an error?

**Comment by Charles546** [comment]
This is released in 1.0.0
