### ISSUE TITLE
cert test failure on OS X with go 1.18

### ISSUE THREAD

**Issue by wyardley** [honeydipper/honeydipper#474]
btw, this test seems to be failing predictably on OS X if you use go v 1.18:

```
    certs_test.go:61: 
        	Error Trace:	certs_test.go:61
        	Error:      	Should NOT be empty, but was []
        	Test:       	TestLoadCACerts
        	Messages:   	system cert pool should not be empty
```

or maybe this change
> On Windows, macOS, and iOS, when a [CertPool](https://tip.golang.org/pkg/crypto/x509/#CertPool) returned by [SystemCertPool](https://tip.golang.org/pkg/crypto/x509/#SystemCertPool) has additional certificates added to it, [Certificate.Verify](https://tip.golang.org/pkg/crypto/x509/#Certificate.Verify) will do two verifications: one using the platform verifier APIs and the system roots, and one using the Go verifier and the additional roots. Chains returned by the platform verifier APIs will be prioritized.

verified that the test passes with the current version of go used (1.17).

**Comment by Charles546** [comment]
This is actually due to 
> [CertPool.Subjects](https://go.dev/pkg/crypto/x509/#CertPool.Subjects) is deprecated. On Windows, macOS, and iOS the [CertPool](https://go.dev/pkg/crypto/x509/#CertPool) returned by [SystemCertPool](https://go.dev/pkg/crypto/x509/#SystemCertPool) will return a pool which does not include system roots in the slice returned by Subjects, as a static list can't appropriately represent the platform policies and might not be available at all from the platform APIs.

The tests rely on counting the `Subjects` to see if it is empty. Without this, we have no way of judging if a cert pool is populated or not.
