### ISSUE TITLE
Dry-run mode

### ISSUE THREAD

**Issue by wyardley** [honeydipper/honeydipper#74]
It may make sense to start early on implementing some kind of dry-run mode for testing, where we log the action that would be taken vs. actually taking it (but still respond to incoming webhooks).

Additionally, making some other interface to force trigger an event locally might be useful.

**Comment by Charles546** [comment]
Prereq for this 

 1) a mock driver to be able to validate input from daemon and produce predefined output to daemon
 2) the ability for operator to substitute one or many drivers with the mock driver based on some kind of config
3) an `injector` service to subsititue the `receiver` to send one or a list of events

An example

```
# MOCK_PLAN should implicitly use LOCALREDIS=1 DEBUG='*'
REPO=. MOCK_PLAN=test.yaml honeydipper
```

The `test.yaml` should look like
```
---
injector:
  - driver: webhook
    rawEvent: ''
    triggeredEvents:
      - github.push
    payload:
        {...}
    wait: 120s
  - triggeredEvents:
    - reload_force

operator:
  mock_drivers:
    - gcloud-gke
    - gcloud-kms
    - kubernetes
